- NOTICE
- licenses/LICENSE-gopkg.txt
- licenses/LICENSE-jaeger-client-go.txt
- licenses/LICENSE-opentracing-go.txt
- licenses/LICENSE-protobuf.txt
- licenses/LICENSE-thrift.txt
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
> chore: add licenses

- bizdemo/easy_note/docker-compose.yml
Signed-off-by: rogerogers <rogers@rogerogers.com>
en: change biz-demo/easy_note docker-compose etcd image, fix run error on mac m1.
zh: 修改easy_note etcd镜像，适配苹果m1
> chore(biz-demo/easy_note): change etcd image

- bizdemo/easy_note/cmd/note/dal/db/init.go
- bizdemo/easy_note/cmd/user/dal/db/init.go
- bizdemo/easy_note/docker-compose.yml
- bizdemo/easy_note/pkg/configs/sql/init.sql
optimize: A new optimization
en: use docker to init db
zh: 使用 docker 来初始化数据库，取代gorm的自动建表功能
null
> optimize: use docker to init database

- opentelemetry/README.md
en: Fix the data source address on the document
zh: 修复文档上的数据源地址
> fix(otel): fix the data source address on the document

- opentelemetry/otel-collector-config.yaml
fix: A bug fix
en: fix wrong path
zh: 修复错误的配置路径
null
> fix: wrong path in otel-collector-config.yaml

- bizdemo/easy_note/cmd/api/main.go
fix: A bug fix
en: Use NoMethod in conjunction with WithHandleMethodNotAllowed
zh: 当使用 NoMethod 时需要与 WithHandleMethodNotAllowed 配合使用
null
> fix: use NoMethod in conjunction with WithHandleMethodNotAllowed

- bizdemo/easy_note/README.md
fix: A bug fix
使用正确的配图，并修正在启动容器时，使用正确的bridge网络。
en:
zh(optional):
> fix: Use the correct illustration; Use the correct bridge network name.

- Dockerfile
fix: Modify the go image in Dockerfile to adapt the go version in go.mod
en: Currently, when compiling projects using Docker Build, errors will occur because the go image version in Dockerfile does not match the go version in go.mod. This submission has fixed this issue
zh(optional):
> fix: Modify the go image in Dockerfile to adapt the go version in go.mod

- bizdemo/easy_note/README.md
- bizdemo/easy_note/README_CN.md
- grpc_multi_service/README.md
- klog/README.md
- klog/README_CN.md
- opentelemetry/README_CN.md
- prometheus/README.md
- prometheus/README_CN.md
- proxyless/README.md
- proxyless/README_CN.md
- tracer/README.md
- tracer/README_CN.md
> feat: add README_ZN

- generic/client/json/example_service.thrift
- generic/client/json/main.go
- generic/server/json/example_service.thrift
- generic/server/json/main.go
> feat: add generic json

- README.md
- README_CN.md
- server_hook/server/main.go
feat
feat: add example of server_hook
> feat: add example of server_hook

- README.md
- README_CN.md
docs
docs: optimize words format
> docs: optimize words format

- README.md
- README_CN.md
> doc: links for thrift streaming in readme

- basic/example_shop/rpc/item/handler.go
> fix: remove untapped param

- README_CN.md
protobuf 使用 Kitex 与 protobuf 生成服务端代码的示例
这句话重复啦一次,中英文档都重复啦一次
> fix: readme statement repetition

- basic/client/main.go
> optimize: simplify basic client and use klog

- metainfo/backward/client/main.go
添加client端获取所有metainfo的API
en:
zh(optional):
最近在开发kitexcall工具的过程中，使用到这个方法，但是发现例子里和官方文档并没有同步展示
---
en: We need you to add run.sh and test.sh for each new example so that users can run and CI test. If you don't know how to add, please refer to the run.sh and test.sh files of other examples.
```
> feat: add receive all the metainfo api

- .github/dependabot.yml
- regenerate-dependabot-config.sh
en:
zh(optional):
---
en: We need you to add run.sh and test.sh for each new example so that users can run and CI test. If you don't know how to add, please refer to the run.sh and test.sh files of other examples.
```
> chore(ci): merge all dependencies into one pull request

- bizdemo/kitex_gorm/handler.go
fix bug
- [✅] This PR title match the format: \<type\>(optional scope): \<description\>
- [✅] The description of this PR title is user-oriented and clear enough for others to understand.
- [✅] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)
更新handler.go文件中的err定义和return返回语句
en:
zh(optional): 在handler.go文件中，service方法的实现定义了返回值的变量名和类型，但是在方法体中又再次使用err := 定义，但是在return的时候却又直接使用return而非return resp, err，导致内部定义的err覆盖了方法声明中的err，造成编译出错。
---
en: We need you to add run.sh and test.sh for each new example so that users can run and CI test. If you don't know how to add, …
> fix: Update handler.go err define && return

- bizdemo/kitex_gorm/docker-compose.yml
fix: 卷映射初始化数据库路径更新，sql文件存放在./model下，而不是./biz/model下
en:
zh(optional):
---
en: We need you to add run.sh and test.sh for each new example so that users can run and CI test. If you don't know how to add, please refer to the run.sh and test.sh files of other examples.
```
> fix: Update kitex-gorm docker-compose.yml

- generic_streaming/pb/client/main.go
- generic_streaming/pb/main.go
- generic_streaming/pb/run.sh
- generic_streaming/pb/test.sh
- generic_streaming/thrift/rpc/main.go
- generic_streaming/thrift/test.sh
fix
en:
zh(optional):
---
en: We need you to add run.sh and test.sh for each new example so that users can run and CI test. If you don't know how to add, please refer to the run.sh and test.sh files of other examples.
```
> fix: generic streaming port conflicts and cleanup issues
